### ISSUE TITLE
Return result,

### ISSUE THREAD

**Issue by karkipy** [yushghimire/js-memomize-log#1]
**Your code**    

    return that.cache[args] ? that.cache[args] : (that.cache[args] = that.apply(this, args));
returns the returned value to be called again
 

 **Solution  Maybe**   

    return that.cache[args] ? that.cache[args] : (that.cache[args] = args[0]);

Note: plus why call the function again? rather just get the result directly, remove return function that way it would make more sense

**Comment by yushghimire** [comment]
@karkipy 
Addressed.
